[build]
  command = "npm run build"
  publish = "build"
  functions = "src/netlify/functions"   # 👈 tells Netlify where your functions are

[build.environment]
  # Tell Netlify to ignore Firebase config (safe to be public)
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_FIREBASE_API_KEY,REACT_APP_FIREBASE_APP_ID,REACT_APP_FIREBASE_AUTH_DOMAIN,REACT_APP_FIREBASE_MESSAGING_SENDER_ID,REACT_APP_FIREBASE_PROJECT_ID,REACT_APP_FIREBASE_STORAGE_BUCKET"
